### ISSUE TITLE
One more character after shortcut

### ISSUE THREAD

**Issue by bagusflyer** [JasonMortonNZ/bs3-sublime-plugin#87] opened 2015-07-11 01:03 UTC
For example, I input <bs3-label it will become:

```
 <<span class="label">Label</span>
```
One extra < input, what's wrong? Thanks

**Comment by pravin-d** [comment] 2015-07-13 12:23
:+1:  Same issue

**Comment by stormslowly** [comment] 2015-07-13 23:50
just type `bs3-xxx`,  the trigger is start with bs3 not <

**Comment by pravin-d** [comment] 2015-07-14 09:51
bs3-xxx does not start the trigger..  however triggering auto completion manually (ctrl+space) does the trick..

**Comment by tobsn** [comment] 2015-07-17 17:31
"auto_complete_triggers": [ {"selector": "text.html", "characters": "<"}, {"selector": "text.html", "characters": "bs3"}, {"selector": "text.php", "characters": "<"} ],

worst case "fix"...

**Comment by mixania** [comment] 2015-08-04 17:36
Can confirm, would be nice if this was fixed without having the user to hack into anything.

**Comment by JasonMortonNZ** [comment] 2016-02-07 01:21
Thanks @tobsn, your fix appears to be the only way past this issue that I've found.

**Closed by JasonMortonNZ** 2016-02-07 01:21 UTC

**Comment by tobsn** [comment] 2016-02-07 01:23
@JasonMortonNZ yeah, the biggest problem isn't the fix, the problem is that the library isn't updated as far as I can tell

**Comment by tobsn** [comment] 2016-02-07 15:19
New Features
  ------------------------------------------------------------
  - FIX FOR remaining '<' after autocomplete:
  	* Update your "auto_complete_triggers" setting to this:
  	* "auto_complete_triggers": [{"selector": "text.html", "characters": "<"},{"selector": "text.html", "characters": "bs3"}]
  - Updated CDN references to Bootstrap v3.3.6
  - OUT NOW     - A PHPStorm plugin with all the same snippets

lol you're welcome :D
