### ISSUE TITLE
"<" stays there hanging after running a snippet

### ISSUE THREAD

**Issue by nmaxcom** [JasonMortonNZ/bs3-sublime-plugin#92] opened 2015-08-05 03:55 UTC
Like so:

![](http://i.imgur.com/svX94ic.png)

**Comment by robinleboe** [comment] 2015-08-15 04:07
Same issue

**Comment by giacom0** [comment] 2015-08-19 10:28
+1

**Comment by wvllvw** [comment] 2015-08-20 12:10
same problem here

**Comment by sishugang** [comment] 2015-08-27 11:45
i have the same problem

**Comment by ablx** [comment] 2015-08-27 19:37
+1

**Comment by CristianCristea** [comment] 2015-09-01 09:32
same problem

**Comment by Beaudinn** [comment] 2015-09-05 15:33
+1

**Comment by wvllvw** [comment] 2015-09-07 11:04
just type bs3 without <

**Comment by thebao** [comment] 2015-09-09 13:22
+1

**Comment by qerim** [comment] 2015-09-16 09:41
+1

Really nice plugin, but this issue get's very annoying.

**Comment by JasonMortonNZ** [comment] 2015-09-16 19:36
I'm looking in to this issue now guys. Can I get you to provide some more info on what versions of Sublime your running and do you have the old Zen Coding plugin install or the HTML5 plugin? Both those plugins have been known to mess with snippets.

@nmaxcom @robertd @giacom0 @wvllvw @sishugang @ablx @CristianCristea @Beaudinn @thebao @qerim

**Comment by qerim** [comment] 2015-09-17 18:21
@JasonMortonNZ 

Thanks for getting back dude!

1) Sublime Text 3 Build 3083 - Portable
2) Windows 7 Enterprise x64, Windows 8.1 Pro x64
3) Plugins Installed: Emmet, AlignTab, HTML Minifier, Markdown Preview, SASS Build, Sass
4) I type "<bs3" and then select from the auto dropdown.

The console just outputs: "command: comit_completion". after I type "<bs3", select and hit Enter.

I just removed the Emmet plugin and tried, but same result.

**Comment by sishugang** [comment] 2015-09-20 05:06
@JasonMortonNZ  thanks very much
1) 3 build 3083
2) win10 enterprise x64
3) plugin :emmet,jquery, pyv8
4) I type "<bs3'  and click , and  console  have no outputs,

**Comment by thebao** [comment] 2015-09-20 13:46
@JasonMortonNZ
 thanks for looking into this
1. Sublime 3 build 3083
2. Ubuntu 14.04
3. Plugins: Better Completion, Bootstrap3, Emmet, Foundation 5, Sass, KnockoutJS
4. "<bs3" + dropdown + TAB. console outputs "command: commit_completion"

**Comment by CronGM** [comment] 2015-09-21 17:20
Plus one. Thanks for looking into in:

1) Sublime Text 3 build 3083
2) Windows 8.1 Enterprise, 64-bit
3) Plugins: Bracket Highlighter, ColorHighlighter, VAlign, jQuery, Minifier, Razor, Sublimerge Pro, 
4) Typing "<bs3-" to trigger the snippets.

**Comment by BoothLuo** [comment] 2015-09-24 05:01
I have the same problem.
1) Sublime Text 3 build 3083
2) Windows 10 Professional , 64-bit
3) Plugins: Emmet , Html-Css-Js-Prettify , Sass , PyV8 , Sublimelinter
4) Typing "<bs3-" or "<bs3" + dropdown + TAB 
There is always a "<" at front of the snippets.

**Comment by benhulan** [comment] 2015-10-08 19:10
+1

1) Sublime Text 3 build 3083
2) Mac OS X 10.10.5
3) Plugins: Emmet, Markdown Preview, Package Control, PyV8, SassBeautify, SFTP, SublimeLinter, SublimeLinter-jshint
4) Typing "<bs", "<bs3" or "<bs3-" and either pressing tab or clicking a selection in the dropdown menu

If I press tab on the default selection, console logs:
'command: insert_best_completion {"default": "	", "exact": false}'
If I click on the selection in the dropdown menu, it changes to "exact":true

Sometimes it also logs cursor moves and command: left_delete, depending on the length of the selection. However, command: left_delete does not appear to remove the leading angle bracket

**Comment by edgarshurtado** [comment] 2015-10-17 07:41
I have the same problem on Mac too. I didn't know about the ctrl + space key shortcut. It solves the issue pretty much for me. Thank you!

**Comment by anburocky3** [comment] 2015-12-07 13:51
Thank you @benhulan  that was  a great shortcut! Helpful :) .. By the way please solve that < (symbol)..
Waiting for the updates :)

**Comment by jiachiun** [comment] 2015-12-17 09:02
I had the same problem but I found a work-around that works for both Sublime 2 and Sublime 3.

You can trigger the snippet shortcut by **pressing Ctrl+Shift+Space**, this will launch the command palette, and you can just type "bs3" and you get the dropdown menu. Then you can just click it or press enter to insert the selected snippet, without an extra "<".

![snippet](https://cloud.githubusercontent.com/assets/5090540/11865553/b22a4f0e-a4df-11e5-8d54-acb3e7e30d7b.jpg)

More advanced option:
Pressing Ctrl+Shift+Space will only launch the command palette. If you want it to launch the command palette and automatically apply a filter for snippets only, you can add this line to Preferences > Key-Bindings - User:

{ "keys": ["ctrl+shift+."], "command": "show_overlay", "args": {"overlay": "command_palette", "text": "Snippet: "}}

Then you can just press **Ctrl+Shift+.** to launch the snippet command.
Of course, you can change the shortcut key to any that you like, like "ctrl+y" etc.

**Comment by eriktobben** [comment] 2015-12-26 20:13
I am having the same problem. Any updates on this issue?

**Comment by wuzhitian** [comment] 2015-12-30 07:35
I am having the same problem. Any updates on this issue?

**Comment by MartinHaun** [comment] 2016-01-28 13:01
Same issue here

**Comment by raedlime** [comment] 2016-02-04 20:48
Same here!

**Comment by JasonMortonNZ** [comment] 2016-02-07 01:16
Hey guys, I've been stumped by the issue for a long time. There's a setting in Sublime called `auto_complete_triggers` and by default it's set to `"auto_complete_triggers": [ {"selector": "text.html", "characters": "<"} ]`. I believe this is the root cause of the '<' remaining.

Unfortunately I can't find much (any) info in the Sublime docs in order to work out if there's a potential fix for this, but as a temporary working solution I updated the setting to `"characters": "bs"`.

Hope that helps guys. Bootstrap 4 snippets is under way an will be released soon :)

**Closed by JasonMortonNZ** 2016-02-07 01:16 UTC

**Comment by raedlime** [comment] 2016-03-25 14:17
awesome! works pretty fine for me!

**Comment by ish3lan** [comment] 2017-01-26 06:29
Took me a while to understand why it is working with every one but me!

After adding 
"auto_complete_triggers": [{"selector": "text.html", "characters": "<"},{"selector": "text.html", "characters": "bs3"}]
to Sublime User Settings.

use bs3 without <. that is (e.g. bs3-form instead of <bs3-form ) and the auto complete
